Api 15228 - Loast tables
department-of-veterans-affairs/lighthouse-docserver pull request #168
Opened 2022-05-04 20:04 UTC by ediiotero

Story: [API-15228](https://vajira.max.gov/browse/API-15228)

Adding loast_result, loast_result_endpoint, and loast_result_exgroup models and interface
Updated Readme and added tests for the models

2022-05-04 20:18 UTC, mheusgit commented on migrations/Migration20220503192847.ts
> +    this.addSql('create table "loast_result" ("id" serial primary key, "created_at" timestamptz(0) not null, "updated_at" timestamptz(0) null, "server" varchar(255) null, "security_type" text check (
loast_result.security_type enum values are not correct.  I ran into this problem as well.

2022-05-04 20:20 UTC, mheusgit commented on src/loast/loastResult/loastResult.model.ts
> +  @Enum({ type: 'SecurityTypeEnum' })
I think the fix for the invalid SQL is to change this to something similar to @Enum(() => SecurityTypeEnum}

2022-05-04 20:24 UTC, mheusgit commented on src/loast/loastResultEndpoint/loastResultEndpoint.model.ts
> +  @Enum({ type: 'MethodEnum' })
Same gotcha

2022-05-04 20:25 UTC, mheusgit commented on migrations/Migration20220503192847.ts
> +    this.addSql('create table "loast_result" ("id" serial primary key, "created_at" timestamptz(0) not null, "updated_at" timestamptz(0) null, "server" varchar(255) null, "security_type" text check (
Same story for loast_result_endpoint.method

2022-05-06 22:33 UTC, dsteeve commented on migrations/Migration20220503192847.ts
> +    this.addSql('create table "loast_result" ("id" serial primary key, "created_at" timestamptz(0) not null, "updated_at" timestamptz(0) null, "server" varchar(255) null, "security_type" text check (
what are the correct values here?  the confluence design doc might need updated. 
I would suggest we stick with the OAS swagger doc definition.

The type of the security scheme. Valid values are "apiKey", "http", "oauth2", "openIdConnect".

so technically we would just have an Enum of "apiKey" and "oauth2" for now?
but in the tests for this PR, it is using SecurityTypeEnum, which is defined with "bearer" and "apikey" which seems to be combining two OAS notions of SecurityType and SecurityScheme - we might need to pow-wow this thru.

2022-05-06 23:22 UTC, christineyost commented on migrations/Migration20220503192847.ts
> +    this.addSql('create table "loast_result" ("id" serial primary key, "created_at" timestamptz(0) not null, "updated_at" timestamptz(0) null, "server" varchar(255) null, "security_type" text check (
Oh dear, not very sure what we should do with this. I was thinking just "oauth" or "apikey" here. From a Lighthouse point of view, today we only support oauth or apikey security. If a provider uses oauth security, they might define it as an "oauth2" security scheme or as an "http" security scheme. Either way we need a token. The other problem is that some APIs define both "http" and "oauth2" security in the same OAS. I'm not sure what we would do with those if we're only allowing one value here

2022-05-13 17:33 UTC, mheusgit approved these changes
Looks good

2022-05-13 21:09 UTC, christineyost reviewed
Looks good to me! I think once "PATCH" is added to the method enum this should be good to go. We should also create a follow up ticket for the loastResultExgroup errors and warnings

2022-05-13 21:09 UTC, christineyost commented on src/loast/loastResultExgroup/loastResultExgroup.interface.ts
> +  warnings: LoastOutput;
I think these will end up being an array of objects like
```
{
  "message": "error/warning message here",
  "count": 3
}
```

Though we may end up adding a type field to this, so I'm ok with leaving a place holder for now. We should be sure to create a ticket to finish this up once the LOAST JSON output ticket is complete

2022-05-16 14:52 UTC, ediiotero commented on src/method/method.enum.ts
> +enum MethodEnum {
thanks! Added PATCH

2022-05-17 21:02 UTC, mheusgit commented
Looks good

2022-05-17 21:02 UTC, mheusgit approved these changes

2022-05-17 21:27 UTC, dsteeve commented on migrations/Migration20220503192847.ts
> +    this.addSql('create table "loast_result" ("id" serial primary key, "created_at" timestamptz(0) not null, "updated_at" timestamptz(0) null, "server" varchar(255) null, "security_type" text check (
leaving security_type as just a string

2022-05-17 21:29 UTC, dsteeve commented on migrations/Migration20220505193149.ts
> +    this.addSql('alter table "loast_result" add constraint "loast_result_security_type_check" check ("security_type" in (\'bearer\', \'apikey\'));');
will this get automatically fixed since we aren't using an enum anymore?

2022-05-17 21:34 UTC, dsteeve commented on src/loast/loastResult/loastResult.interface.ts
> +import SecurityTypeEnum from '../../api/security/securityType.enum';
I think this import can be deleted now

2022-05-17 22:49 UTC, dsteeve requested changes
I think to make these changes, you will need to delete the current migration files and re-run the mikro-orm migration:up and then mirko-orm mirgration:create -- then the migration files should look correct in your PR.

2022-05-17 22:49 UTC, dsteeve commented on README.md
> +| security_type  | Text  | Yes | "apiKey" or "oauth" | apiKey | Flag indicating whether apikey or oauth security was used for this LOAST test |
I"ve changed my mind since our earlier meeting today @ediiotero - 
After seeing we already have a securityType.enum in our code and after further discussing with @christineyost we decided a better name for this field would be "authentication_type"  This can then be an enum of "apikey" and "oauth". This follows along the lines of what this person wrote for different authentication types.  https://idratherbewriting.com/learnapidoc/docapis_more_about_authorization.html


This feels better to not confuse people.  Then all your tests you have will need to reference this new AuthenticationType.enum and not the securityTypeEnum that they are currently importing.

2022-05-17 22:49 UTC, dsteeve commented on src/method/method.enum.ts
> +enum MethodEnum {
I think it would be better to have this live under the loast folder for now.

2022-05-17 22:52 UTC, dsteeve commented on test/loast/loastResult/loastResult.model.test.ts
> +import SecurityTypeEnum from '../../../src/api/security/securityType.enum';
these would then be changed to be authenticationType.enum to not confuse people because I think this test will still work as is.

2022-05-23 16:42 UTC, dsteeve approved these changes
looks good to me!  Were the text fields going to be varchar still, or a separate ticket?

2022-05-23 16:56 UTC, christineyost approved these changes
Looks good to me!
As mentioned in the code comments, we can update the LoastOutput interface when API-15225 is worked

2022-05-23 18:36 UTC, ediiotero commented
I added updating the LoastOutput interface to the AC for API-15225

2022-05-23 18:37 UTC, merged