Api 14296/size limit gateway response
department-of-veterans-affairs/lighthouse-docserver pull request #205
Opened 2022-09-14 14:50 UTC by ediiotero

Story: [API-14296](https://vajira.max.gov/browse/API-14296)

Update Responses in OAS transformer to support the size limit plugin

I used a 413 but open to feedback from the team

2022-09-19 18:02 UTC, mheusgit commented on test/fixtures/gatewayResponses.ts
> +  '413': {
Not sure why we are not reusing the exports from "src/oas/transformer/resources/gatewayResponses.ts" for the fixture and friends

2022-09-28 20:29 UTC, mheusgit commented on src/oas/transformer/resources/gatewayResponses.ts
> +  description: 'Payload too large',
It so odd that shortly after this PR was created but not merged that DocServer started generating "413" type errors for LOAST results in [API-18995](https://vajira.max.gov/browse/API-18995).  

Just leaving this comment for tracking.

2022-09-28 20:30 UTC, mheusgit approved these changes

2022-09-28 20:30 UTC, mheusgit commented on test/fixtures/gatewayResponses.ts
> +  '413': {
I'll let ticket creator decide if this should be cleaned up.

2022-09-30 22:22 UTC, dsteeve commented on src/oas/transformer/resources/gatewayResponses.ts
> +  description: 'Payload too large',
that is very curious?

2022-09-30 22:29 UTC, dsteeve commented on test/fixtures/gatewayResponses.ts
> +  '413': {
I would say that makes sense as well.  It is just exporting constants.

2022-09-30 22:31 UTC, mheusgit commented on src/oas/transformer/resources/gatewayResponses.ts
> +  description: 'Payload too large',
No.  Its just to avoid confusion when the bug fix goes in for Express 413.  It not connected to this change.

2022-09-30 22:33 UTC, dsteeve requested changes
if we have the time, we should do the test fix.  Also blocking this until the actual Kong changes are closer to production, otherwise we will potentially have this 413 added to all the OAS's in production docserver before Kong changes are actually live.

2022-10-20 23:24 UTC, dsteeve approved these changes
I think this can go in now, even if the gateway change lags a bit.

2022-10-24 16:11 UTC, merged