[API-25396] Add optional query parameter to show s3 status for api versions
department-of-veterans-affairs/lighthouse-docserver pull request #273
Opened 2023-04-13 20:40 UTC by jeremyhwu

2023-04-14 19:30 UTC, christineyost commented on src/api/version/apiVersion.controller.ts
> +        const metadata = JSON.parse(s3ResponseString) as Metadata;
Might be nice to add a function to the PortalStoreService that gets metadata by API name. If we ever need to switch from S3 to a different datastore that way our changes will all be in the PortalStoreService instead of throughout the code

2023-04-14 22:40 UTC, christineyost commented on src/utils/s3.service.ts
> +    }
Need to handle the file not existing. If the metadata file does not exist then none of the versions are published

2023-04-14 22:40 UTC, christineyost commented on src/utils/s3.service.ts
> +      });
This might be able to be simplified using `sdkStreamMixin(response.Body).transformToString()`

`sdkStreamMixin` comes from `@aws-sdk/util-stream-node`

2023-04-17 18:01 UTC, jeremyhwu commented on src/utils/s3.service.ts
> +    }
This is now handled in the `getMetadata` function from `PortalStoreService`.

2023-04-17 18:02 UTC, jeremyhwu commented on src/api/version/apiVersion.controller.ts
> +        const metadata = JSON.parse(s3ResponseString) as Metadata;
Added in latest commit

2023-04-18 23:03 UTC, christineyost commented on src/portalStore/portalStore.service.ts
> +    }
I think this makes sense to me - if fetching metadata from S3 results in any kind of error, treat it as if no APIVersions are published for the API. Just want to double check with @dsteeve on this

2023-04-19 18:50 UTC, dsteeve requested changes

2023-04-19 18:50 UTC, dsteeve commented on src/portalStore/portalStore.service.ts
> +    }
I think it might make sense to add a static method to metadata.model.ts that returns a default empty Metadata with the "meta: { versions: [],}. instead of having it inline here.  Reason being is that this could be a bug over time when the interface changes - and having it in a method with the model will more likely get caught and changed by a developer if/when the interface changes.

I also think we can't assume that any error should do this, but hopefully we can only do this when it is a 404 error (nothing found) from the s3Service. It is possible that the network is down or AWS is down, then we want to do something different and maybe don't put the "publish" in there at all if it is a 500 error from AWS.

2023-04-19 18:50 UTC, dsteeve commented on src/api/version/apiVersion.controller.ts
> +      if (include_published === 'true') {
This feels like too much business logic at the controller level.  Typically I think the pattern has been for the service or manager to return a model and then the controller takes the model and builds the response.  

Since this controller already has the APIVersionManager, I would suggest that it get used and this logic get pushed into there.  
Perhaps a apiVersionManager.getAPIVersionsForAPI that takes the api, and this include_published as parameters. 

Then, it calls the apiVersionService and the portalStoreService coming back with the array of apiVersionModel filled in.  The apiVersionModel can then be used by the controller to create the response object.  

Unit testing might become easier as well with this approach

2023-04-19 21:33 UTC, mheusgit reviewed
Did a review of current state.  The main item noticed was mentioned by dsteeve concerning working with PortalStore in the controller.  Prefer to use the manager class for that

2023-04-25 17:55 UTC, christineyost commented on src/api/version/apiVersion.manager.ts
> +
I'd suggest combining these two methods into one. I think we could do something like:

```
  public async getAPIVersionsForAPI(
    api: APIModel,
    include_published = false,
  ): Promise<APIVersionModel[]> {
    let apiVersions: APIVersionModel[];
    try {
      const versions = await api.versions.init({
        orderBy: { version: 'desc' },
        populate: ['loastConfig.suites'],
      });

      apiVersions = versions.getItems();
    } catch (err) {
      throw new ServerError(
        err as Error,
        `Getting versions for API ${api.name}`,
      );
    }

    if (include_published === true) {
      let metadata: Metadata;
      try {
        metadata = await this.portalStoreService.getMetadata(api);
      } catch (err) {
        return apiVersions;
      }

      const publishedVersions = metadata.meta.versions.map(
        (version) => version.version,
      );

      for (const apiVersion of apiVersions) {
        if (publishedVersions.includes(apiVersion.version)) {
          apiVersion.published = true;
        } else {
          apiVersion.published = false;
        }
      }
    }

    return apiVersions;
  }
```

Then in APIVersionController this getAPIVersionsForAPI function can be called instead of listAPIVersionsForAPI

2023-04-25 17:55 UTC, christineyost commented on test/fixtures/apiVersions.ts
> +);
It may be possible to use existing APIVersion fixtures instead of creating new ones. If you want one to be v0 and one to be v1 you could use `apiVersionKeyRemovePath` and `apiVersionAPIKeyAndRoute`

2023-04-25 19:52 UTC, christineyost commented on test/api/version/apiVersion.controller.test.ts
> +it('returns a 200 and apiVersion data but does not show s3 published status', async () => {
```suggestion
it('APIVersionController.getAPIVersionsForAPI() returns a 200 and apiVersion data but does not show s3 published status', async () => {
```

Marc introduced this new pattern of not using `describe` statements and including "<class>.<method>()" at the beginning of each test description

2023-04-25 19:52 UTC, christineyost commented on test/api/version/apiVersion.controller.test.ts
> +it('returns a 200, apiVersion data, and includes s3 published status', async () => {
```suggestion
it('APIVersionController.getAPIVersionsForAPI() returns a 200, apiVersion data, and includes s3 published status', async () => {
```

2023-04-25 19:52 UTC, christineyost commented on test/api/version/apiVersion.manager.test.ts
> +});
I think this is the same test as the one just above. It can be removed

2023-04-25 19:52 UTC, christineyost commented on test/api/version/apiVersion.manager.test.ts
> +describe('getAPIVersionsForAPI', () => {
Similar to the APIVersionController test... the describe statement can be removed and add `APIVersionManager. getAPIVersionsForAPI()` to the beginning of each description in the it statements.

We're also trying to move away from having `beforeEach` functions, except at the root of the test file. Instead of having the before each here this mock can be added to the beginning of each of these tests that needs it

2023-04-26 23:09 UTC, christineyost approved these changes
Changes look good to me! Tested the query parameter locally as well as generating metadata and running LOAST via API batch

2023-04-28 19:46 UTC, dsteeve approved these changes
one small typo I noticed, but I brought it down, tested it.  Looks Good!

2023-05-02 16:09 UTC, merged