API-23430/Slack dashboard URLs
department-of-veterans-affairs/lighthouse-docserver pull request #283
Opened 2023-05-03 22:09 UTC by ediiotero

Story: [API-23430](https://vajira.max.gov/browse/API-23430)

Update Slack URLs to match changes on the portal to include the env in the URL.

2023-05-04 17:12 UTC, mheusgit commented on src/config.ts
> +    `https://hub.lighthouse.va.gov/provider-dashboard/apis/{API_NAME}/${portalEnv}/versions/{VERSION}/loast`,
The dashboard URLs were originally designed to closely match the actual request on DocServer side.  I prefer if the env path param proceeds the rest.

https://hub.lighthouse.va.gov/provider-dashboard/${portalEnv}/apis/{API_NAME}/versions/{VERSION}/loast

2023-05-15 16:43 UTC, mheusgit commented on src/config.ts
> +  portalEnv = PortalEnv.QA;
The logic does not appear to support links to DocServer staging or prod

2023-05-15 18:52 UTC, ediiotero commented on src/config.ts
> +  portalEnv = PortalEnv.QA;
I might be missing something but `portalEnv` is set to the current `env` that could be staging, dev, or prod. The `If` is only there to change it from dev to qa to be in line with the links on the portal.

2023-05-15 19:01 UTC, mheusgit commented on src/config.ts
> +  portalEnv = PortalEnv.QA;
I misread it.  Your good then

2023-05-15 19:01 UTC, mheusgit submitted a review, later dismissed
Looks good

2023-06-16 22:52 UTC, dsteeve approved these changes
I like the "dashboardEnvContext" change.  I think this aligns better with the future for it to be DEV.  

I realize the actual docserver context is QA (which is our DEV) -- because blue.{env}.lighthouse.va.gov doesn't have a DEV.  However the future will be LHDI which does have a DEV and a QA but that QA is more like STAGING.  LHDI won't have a STAGING, so thus I think DEV is a better choice here.  

LOL! I don't think any sane person can read that above paragraph.

2023-06-16 23:14 UTC, dsteeve commented
> I like the "dashboardEnvContext" change. I think this aligns better with the future for it to be DEV.
> 
> I realize the actual docserver context is QA (which is our DEV) -- because blue.{env}.lighthouse.va.gov doesn't have a DEV. However the future will be LHDI which does have a DEV and a QA but that QA is more like STAGING. LHDI won't have a STAGING, so thus I think DEV is a better choice here.
> 
> LOL! I don't think any sane person can read that above paragraph.

Actually, think this value needs to remain as 'qa' for now -- and change that to 'dev' as a separate ticket.

2023-06-16 23:16 UTC, dsteeve requested changes
--QA is an env highly baked into the provider dashboard at  the moment, so will make that change to DEV as a separate effort.

2023-06-16 23:17 UTC, dsteeve approved these changes
looks good!

2023-06-23 17:10 UTC, merged