API-26012/  doc server  implement gateway service caching
department-of-veterans-affairs/lighthouse-docserver pull request #286
Opened 2023-05-10 21:47 UTC by mheusgit

- Updated Axios version from 0.21.1 to 1.3.4
- Installed axios-cache-interceptor & node-cron.  New modules trigger bi-daily caching of gateway entities
- GatewayServiceConfig, APIVersionService, and NotificationService moved to a new HTTPClient to centralize axios logic
- Implemented controller & endpoint '/cache/gateway'.  Logic depends on a new CachedHTTPClient to handle caching
- ServiceInjector no longer handles gateway, Slack, or AWS configurations instead its dealt with in the relevant service

2023-06-15 23:22 UTC, christineyost reviewed
I read a couple places that the `node-cron schedule` function doesn't work with async functions. We might need to consider instead using `node-schedule` or the existing `lighthouse-platform-tasks` solution.

I also wonder if we should update the Docserver OAS as part of a separate ticket again because I think we have several changes that are missing at this point

2023-06-20 19:59 UTC, mheusgit commented on docs/docserver_oas.json
> +                  "type": "null",
Its autogenerated

2023-06-20 20:02 UTC, mheusgit commented on docs/docserver_oas.json
> +                  },
Its autogenerated.  The tool realizes there is property to pass but didn't detect a test passing a value

2023-06-20 20:06 UTC, mheusgit commented on src/app.ts
> +    },
Yes.  The logic received a number of test.  I'll check for the exact problem it has with async.  End of day the cron doesn't need to return a value.  I bet that is where some DEVs ran into trouble.

2023-06-20 20:12 UTC, mheusgit commented on docs/docserver_oas.json
> +                  "type": "null",
For future reference only the summarys, descriptions, security declarations, and a 2 or 3 param declarations in docserver_oas_base.json are not autogenerated.  Everything else is from the tool.

2023-06-20 20:48 UTC, mheusgit commented on src/app.ts
> +    },
After further digging around I see async used in a number of places for this module.  There is only one comment in Stackoverflow saying otherwise.

2023-06-20 21:26 UTC, mheusgit commented on src/app.ts
> +    },
Looked over this further with @christineyost .  

The type were added but the module devs did not write this package.  There are subtle differences.  From looking at the code using a async should work but trying to use a value from the returned function probably cannot be done.  Current usage does not expect this anyhow.

2023-06-20 21:39 UTC, mheusgit commented
PR should be in better shape

2023-06-20 23:46 UTC, christineyost reviewed
Looks good to me! 

Not sure if @dsteeve might want to take a look?

2023-06-20 23:46 UTC, christineyost commented on src/app.ts
> +    },
I think this is better. 

To fix the remaining eslint disable we could do a PR on the `definitelytyped` github repo adding the Promise<any> type as a return type of the function. I saw an [equivalent PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60104) on the `node-schedule` types. Definitely not needed for this change, but it might be nice to sometime look though the eslint disables we have and see if we can fix any

2023-07-14 00:01 UTC, mheusgit commented
package-lock.json probably needs to be regenerated.  Merging it is no good

2023-07-14 00:03 UTC, mheusgit commented
As expected it created build errors.

2023-07-14 22:57 UTC, dsteeve requested changes
Overall, I like the revamp and cleanup done here, but had a couple questions.

2023-07-14 22:57 UTC, dsteeve commented on src/gateway/gateway.service.ts
>        if (response.status !== 200) {
a better error here might give the status it did receive to assist in troubleshooting

2023-07-14 22:57 UTC, dsteeve commented on src/utils/cachedHTTPClient.ts
> +        ttl: 1000 * 60 * 60 * 24 * 7, // Week in milliseconds
this is interesting and I recommend some documentation in our quokka team page for docserver.  this could cause confusion down the road when things begin to move slow after a week because cacher wasn't working and then all the cache is deleted.

2023-07-14 22:57 UTC, dsteeve commented on test/notification/notification.service.test.ts
> +it('NotivicationService.defaultConfig() returns error on missing values', () => {
typo NotificationService.

2023-07-14 22:57 UTC, dsteeve commented on src/gateway/gateway.service.ts
> +class GatewayService extends CachedHTTPClient {
at first glance, it feels weird to extend an HTTP client here.  Seems like that is more a "has a" relationship vs "is a".  Wondering why this choice?

2023-07-14 22:57 UTC, dsteeve commented on src/notification/notification.service.ts
> +  extends HTTPClient
again, seems weird to extend an HTTPClient for a Service.

2023-07-14 22:57 UTC, dsteeve commented on src/api/version/apiVersion.service.ts
> -    this.client = axios.create({
definitely like moving this code out and just bringing in the httpclient.

2023-07-14 23:02 UTC, dsteeve commented on src/cache/cache.controller.ts
> +}
one of my comments got deleted somehow. 
curious if refreshCache will totally delete all cache and rebuild?  OR do we need a way to delete the old cache? 
past experience with caching is "refresh" did more of a replace of existing cache -- but if one item in the cache wasn't replaced (because it didn't exist in the data coming back anymore) - that one item sticks around until its TTL comes due.  

will that happen with this?  I need time to test that.

https://axios-cache-interceptor.js.org/guide/invalidating-cache

2023-07-17 17:02 UTC, mheusgit commented on src/gateway/gateway.service.ts
>        if (response.status !== 200) {
This comment is tied to a section of code that was untouched

2023-07-17 17:05 UTC, mheusgit commented on src/utils/cachedHTTPClient.ts
> +        ttl: 1000 * 60 * 60 * 24 * 7, // Week in milliseconds
I could swear this was already documented.  Going to check

2023-07-17 17:14 UTC, mheusgit commented on src/gateway/gateway.service.ts
> +class GatewayService extends CachedHTTPClient {
Several services were already acting as HTTPClients.  This PR simply made the relationship more explicit.

2023-07-17 17:19 UTC, mheusgit commented on src/notification/notification.service.ts
> +  extends HTTPClient
See above

2023-07-17 17:20 UTC, mheusgit commented on src/api/version/apiVersion.service.ts
> -    this.client = axios.create({
Code following the previous convention is doomed in the long term.

2023-07-17 18:38 UTC, mheusgit commented on src/cache/cache.controller.ts
> +}
No, its on a URL by URL basis in CachedHTTPClient.refreshPaginatedCache()

Both the "override" and "staleIfError" flags are used to instruct axios-cache-interceptor to give desired behavior.  
From the website:
stalteIfError: Enables cache to be returned if the response comes with an error, either by invalid status code, network errors and etc.

override: This option bypasses the current cache and always make a new http request. This will not delete the current cache, it will just replace the cache when the response arrives.

Both settings were tested to confirm they work as desired.

2023-07-17 18:39 UTC, mheusgit commented on src/cache/cache.controller.ts
> +}
ttl is used at the fallback of last resort.  In this case it has the extra long time to live

2023-07-17 23:17 UTC, dsteeve commented on src/cache/cache.controller.ts
> +}
yep, just wondering - and it sounds like it isn't feasible - if we should have a "trashAllCache" in the event that stale data from cache is returning and we want to start over.  Sounds like a restart of the server would do the trick?

2023-07-17 23:19 UTC, dsteeve commented on src/gateway/gateway.service.ts
> +class GatewayService extends CachedHTTPClient {
I would say that services were using HTTPClients and were not An HTTPClient. I would like it to have a client and not be extending from a client.  Reason being, I can see a close future where there is a baseService class that owns (not extends) the HttpClient -- and we can just extend from the baseService class.

2023-07-17 23:20 UTC, dsteeve commented on src/gateway/gateway.service.ts
>        if (response.status !== 200) {
ok, I will create a separate ticket.

2023-07-17 23:47 UTC, dsteeve commented on src/utils/cachedHTTPClient.ts
> +        ttl: 1000 * 60 * 60 * 24 * 7, // Week in milliseconds
are you saying it was documented in the ticket?  I was asking for documentation that was part of the ReadMe that caching of http cache exists and will expire based on the ttl configured in cachedHttpClient.ts

2023-07-17 23:49 UTC, dsteeve commented on src/gateway/gateway.service.ts
> +class GatewayService extends CachedHTTPClient {
I created a separate ticket for this, but since this introduced the httpClient and the cachedHTTPClient, I feel like it should be corrected as part of this ticket.

2023-07-18 00:06 UTC, mheusgit commented on src/cache/cache.controller.ts
> +}
To clear or "trash" the cache you call CachedHTTPClient.refreshPaginatedCache() method or the new "POST:/cache/gateway" endpoint.

2023-07-18 00:21 UTC, mheusgit commented on src/gateway/gateway.service.ts
> +class GatewayService extends CachedHTTPClient {
Before you go down that route you might want to consider how you'll support overriding the client methods & interceptors.  Previously logic dealt with this by redundancies.

2023-07-18 00:28 UTC, mheusgit commented on src/gateway/gateway.service.ts
> +class GatewayService extends CachedHTTPClient {
Sounds like this is less of a class structure issue and more the verbiage of "client" causing confusion.

2023-07-18 14:21 UTC, dsteeve commented on src/gateway/gateway.service.ts
> +class GatewayService extends CachedHTTPClient {
no, that is not my concern.

2023-07-18 23:06 UTC, dsteeve commented on src/gateway/gateway.service.ts
> +class GatewayService extends CachedHTTPClient {
will go with current state with promise of future conversations over concerns.

2023-07-18 23:10 UTC, dsteeve commented on src/api/version/apiVersion.service.ts
> -    this.client = axios.create({
will go with current state with promise of future conversations over concerns -- 

One recommendation is to move this httpClient out of the utils package and create an "http" package.  Then the interceptors can live there -- and when creating a client you could use default interceptors or a special crafted one like NotificationService uses. Then these interceptors could get reused. 

I see a future where clients might be graphQL -- tying a service business code to http could be limiting.

2023-07-19 16:46 UTC, mheusgit commented
PR merge must wait until after upcoming MR is completed

2023-07-19 18:47 UTC, dsteeve approved these changes

2023-07-19 19:33 UTC, mheusgit commented
MR has been performed and no longer blocks this PR

2023-07-19 20:16 UTC, merged