[API-27047] Add 'differs' property when S3 metadata is out of sync
department-of-veterans-affairs/lighthouse-docserver pull request #301
Opened 2023-06-27 21:09 UTC by jeremyhwu

2023-07-05 22:18 UTC, dsteeve requested changes

2023-07-05 22:18 UTC, dsteeve commented on src/api/metadata/metadata.service.ts
>    public async generateMetadata(api: APIModel): Promise<Metadata> {
2 functions with different names work, but it would be possible to have "generateMetadata" with an optional apiVersions parameter -- and if they didn't supply it, you could go get it -- might be a better alternative?  

 I like the idea of breaking up the logic to decide if you have versions and go get them - separate from actual generating the metadata.  Seems easier to test too.  
 
 Basically one public function of generateMetadata with optional versions param supplied.  With one private function to format results.

2023-07-06 01:48 UTC, jeremyhwu commented on src/api/metadata/metadata.service.ts
>    public async generateMetadata(api: APIModel): Promise<Metadata> {
Having an optional `apiVersions` parameter on the function is what I wanted to do originally as well, seemed cleaner.

However, doing it that way creates a circular dependency. The metadata service calls `this.apiVersionManager.getAPIVersionsForAPI(api)` to retrieve the API Version list, and requires an instance of the `apiVersionManager` in the constructor. Since I'm trying to use the `generateMetadata` function in the `apiVersionManager` as well, I had to move the code out into a public function that isn't a class method of the metadata service. Otherwise, I wouldn't be able to import the function into the manager.

2023-07-06 21:39 UTC, jeremyhwu commented on src/api/metadata/metadata.service.ts
>    public async generateMetadata(api: APIModel): Promise<Metadata> {
I did a bit of a refactor using Christine's suggestions and `generateMetadata` now has an optional `apiVersions` parameter. I also created a private function to format the metadata results as suggested above.

2023-07-07 23:30 UTC, christineyost reviewed
`npm run build` resulted in some build errors. Those should be fixed along with these changes.

The APIVersionManager refactor looks good to me though! Also tested locally and the `published` property is set on responses as expected.

2023-07-10 17:37 UTC, christineyost approved these changes
Looks good to me!

2023-07-11 19:42 UTC, dsteeve approved these changes
ran build locally and reviewed latest changes.  I like the refactor, I think we are on a better track now.

2023-07-11 19:49 UTC, merged