API-26072 fix broken test.  healthcheck import coming in undefined
department-of-veterans-affairs/lighthouse-docserver pull request #318
Opened 2023-07-28 22:28 UTC by dsteeve

fix broken test because import wasn't being brought in

2023-07-28 22:30 UTC, christineyost approved these changes

2023-07-28 23:13 UTC, christineyost requested changes
Changing oneRingServer's api fixture import would fix this. But a better fix might be moving the healthcheck constant to a fixture file. It seems like more of an APIVersion fixture than something related to the oneRingServer

2023-07-31 14:58 UTC, dsteeve commented
> Changing oneRingServer's api fixture import would fix this. But a better fix might be moving the healthcheck constant to a fixture file. It seems like more of an APIVersion fixture than something related to the oneRingServer

yes, that is a better long term fix.

2023-07-31 15:58 UTC, mheusgit approved these changes

2023-07-31 16:06 UTC, christineyost approved these changes

2023-07-31 16:38 UTC, merged

2023-07-31 17:17 UTC, stevelong00 reviewed
Looks good!